from copy import deepcopy

player_cols = [
    'AFLfantasy',
    'Supercoach',
    'behinds',
    'bounces',
    'brownlow',
    'clangers',
    'clearances',
    'contested_marks',
    'contested_poss',
    'disposals',
    'first_name',
    'frees_against',
    'frees_for',
    'fullkey',
    'fullname',
    'goal_assists',
    'goals',
    'handballs',
    'hitouts',
    'homeAway',
    'inside50',
    'kicks',
    'last_name',
    'marks',
    'marks_in_50',
    'matchid',
    'namekey',
    'number',
    'one_percenters',
    'playerid',
    'rebound50',
    'tackles',
    'team',
    'tog',
    'uncontested_poss',
    'centre_clearances',
    'disposal_efficiency',
    'effective_disposals',
    'intercepts',
    'metres_gained',
    'stoppage_clearances',
    'score_involvements',
    'tackles_in_50',
    'turnovers',
    'season',
    'round'
]

player_cols_to_agg = [
    'AFLfantasy',
    'Supercoach',
    'behinds',
    'bounces',
    'brownlow',
    'clangers',
    'clearances',
    'contested_marks',
    'contested_poss',
    'disposals',
    'frees_against',
    'frees_for',
    'goal_assists',
    'goals',
    'handballs',
    'hitouts',
    'inside50',
    'kicks',
    'marks',
    'marks_in_50',
    'one_percenters',
    'rebound50',
    'tackles',
    'tog',
    'uncontested_poss',
    'centre_clearances',
    'disposal_efficiency',
    'effective_disposals',
    'intercepts',
    'metres_gained',
    'stoppage_clearances',
    'score_involvements',
    'tackles_in_50',
    'turnovers',
    'matchid',
    'next_matchid',
    'team'
]

player_cols_to_pg = deepcopy(player_cols_to_agg)
player_cols_to_pg.remove('matchid')
player_cols_to_pg.remove('team')
career_cols_to_pg = ['career_' + col for col in player_cols_to_pg]
season_cols_to_pg = ['season_' + col for col in player_cols_to_pg]
player_cols_to_pg.extend(career_cols_to_pg)
player_cols_to_pg.extend(season_cols_to_pg)